# Generated by Django 3.0.7 on 2020-06-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_granada', '0004_auto_20200619_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='nombre',
            field=models.CharField(default='', max_length=155, unique=True),
        ),
    ]
