# Generated by Django 3.0.7 on 2020-06-19 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitas_granada', '0005_auto_20200619_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='nombre',
            field=models.CharField(max_length=155, unique=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visita', to=settings.AUTH_USER_MODEL),
        ),
    ]
