# Generated by Django 3.0.7 on 2020-06-19 08:39

import django.core.validators
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_granada', '0006_auto_20200619_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='foto',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='fotos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
    ]
