version: '3'

services:  
  app_django:
    build: . 
    ports: 
      - "8000:8000"
    volumes:
      - ./django_app/static:/code/static            # para los archivos static
      - ./django_app/media:/code/media  # para los archivos media
      - ./:/code                        # para los archivos de la api    

  nginx:
    image: nginx:alpine    
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d/:/etc/nginx/conf.d    # dir para archivo configuración de nginx 
      - ./django_app/static:/code/static                         # para los archivos static
      - ./django_app/media:/code/media              # para los archivos media     
    depends_on:
      - app_django
  
  app_react:
    image: node:12-alpine       
    volumes:
      - ./react_app:/code:cached     
    working_dir: /code
    ports:
      - "3000:3000"
    command: npm start 
    tty: true
    
  
volumes:
  .:
