# Generated by Django 3.0.7 on 2020-06-19 06:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import visitas_granada.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=155, unique=True)),
                ('descripcion', models.CharField(max_length=1000, validators=[visitas_granada.models.validate_capitalized])),
                ('likes', models.IntegerField(default=0)),
                ('foto', sorl.thumbnail.fields.ImageField(blank=True, upload_to='fotos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jgp', 'png'])])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visita', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitas_granada.Visita')),
            ],
        ),
    ]
