# Generated by Django 3.0.7 on 2020-06-19 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitas_granada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='visita', to=settings.AUTH_USER_MODEL),
        ),
    ]
