# Generated by Django 3.0.3 on 2020-03-04 13:23

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_granada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='foto',
            field=models.FileField(blank=True, upload_to=django.core.files.storage.FileSystemStorage(location='/media/fotos')),
        ),
    ]
