# Generated by Django 3.0.3 on 2020-03-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_granada', '0004_auto_20200304_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='foto',
            field=models.FileField(blank=True, upload_to='fotos'),
        ),
    ]
