# Generated by Django 3.0.7 on 2020-06-19 18:10

from django.conf import settings
import django.contrib.auth
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitas_granada', '0007_auto_20200619_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='owner',
            field=models.ForeignKey(default=django.contrib.auth.get_user_model, on_delete=django.db.models.deletion.CASCADE, related_name='visita', to=settings.AUTH_USER_MODEL),
        ),
    ]
